### ISSUE TITLE
GPS initiated when EggTimer opened

### ISSUE THREAD

**Issue by aaronkjones** [pedlarstudios/EggTimer#3]
When I launch the app, I get the indication, "GPS ready." I think this is causing unnecessary battery draining. I have no development experience, but I will try to educate myself on why it is happening and maybe how it can be fixed. Maybe it is not even a problem. If so, I apologize.

**Comment by bhawker** [comment]
Hi fastholds,

Thank you for the feedback. I've seen one other person report this happening, though I have never seen it on my device personally. The EggTimer app does not require or use GPS at all, so I'm wondering if this is happening due to a bug with a particular version of the Garmin software on the Vivoactive, and how it interacts with EggTimer.

Could you let me know what version of the app you have, and also what the Connect IQ and other versions of the device are? The app version I believe you can see from the Connect IQ app on your phone or computer. Those other versions you can see in Settings -> System -> About (Display Version, Connect IQ Version, etc).

Thanks.

**Comment by aaronkjones** [comment]
I can say that it has not enabled GPS always. There was a certain point when it began and before that it never did it. I tried removing and reinstalling it. I'm not sure what changed though. Here is the version info,

Build Type Release
Build Ver.3.6.0.1
Install ID487bfb9b-ebb9-41feae32-3fa52ee8d5bc
Pref Ver.32

Using Android 6.0.1

**Comment by aaronkjones** [comment]
I did a little experiment tonight. I charged my vivoactive to 100% and set a timer for 1 hour and 1 second. At the end of the timer my battery was 90%. I will report back once an hour of no timer running is complete.

**Comment by aaronkjones** [comment]
So, 1 hour with no timer running ended with 99% batter versus 90% with timer running. It seems to definitely be using GPS during operation. I will continue to investigate why.

**Comment by bhawker** [comment]
I found this forum post, where a couple of users have mentioned that as of version 3.5 firmware on the Vivoactive (and I would guess 3.6, the version you have), that if GPS is enabled in Settings, when a downloaded Connect IQ app (like EggTimer) is opened, GPS starts up. I was able to replicate this on my watch running version 3.5. Hopefully Garmin will change this back and fix it so that only apps that require GPS do this.

https://forums.garmin.com/showthread.php?348685-VivoActive-Battery-Draining-fast

**Comment by aaronkjones** [comment]
Good to know. One person mentioned that having GPS disabled in settings does not affect GPS starting when beginning an activity. I will try doing that and see if it has an effect on this battery drain problem.

**Comment by aaronkjones** [comment]
So by disabling GPS in settings, apps like EggTimer do not initiate GPS (so far). Thanks for helping me figure this out. I guess this can be closed since it is a Garmin problem and not an EggTimer problem ;)

**Comment by bhawker** [comment]
No problem, I'm glad we could get to the bottom of it :)
